import type { Metadata } from "next";
import "./globals.css";
import { NextAuthProvider } from "@/components/providers/next-auth-provider";
import { LoadingProvider } from "@/components/providers/loading-provider";
import { Toaster } from "sonner";

import {  Roboto } from 'next/font/google';

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Tisog interventor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NextAuthProvider>
    <html className={`${roboto.className} antialiased`} lang="es">
      <LoadingProvider>
        <Toaster richColors position="top-center" />
        {children}
      </LoadingProvider>
    </html>
  </NextAuthProvider>
  );
}
